### ISSUE TITLE
Duplicate references in Markdown with --reference-location=section

### ISSUE THREAD

**Issue by laperouse** [jgm/pandoc#3674]
I have a docx file with a table with a images.
If I convert it to md using this command:
Pandoc -s -t markdown-pipe_tables-multiline_tables-simple_tables -o "documentation.md" --extract-media=aaaaaaa-aaaaaaaaaaaaa-aaaaa --atx-headers  "aaaaaaaaaaaaaaa.docx"

then i get this:
```
+-----------------------------------+-----------------------------------+
| Format provided in dddd dddddd    | Result displayed on the ddddd     |
| for the dddd dddddddd             |                                   |
+===================================+===================================+
| ![](aaaaaaa-aaaaaaaaaaaaa-aaaaa/m | ![](aaaaaaa-aaaaaaaaaaaaa-aaaaa/m |
| edia/image34.png){width="3.215972 | edia/image35.png){width="2.232000 |
| 2222222222in"                     | 2187226597in"                     |
| height="0.4798611111111111in"}    | height="0.43785214348206475in"}   |
+-----------------------------------+-----------------------------------+
```
the image links are multilined.
If I try to reparse this into docx i get a warning saying that the image is not found because the url is wrong, it thinks there is a space between m and e in media. It is just when there is the linebreak.
```
[pandoc warning] Could not find image `aaaaaaa-aaaaaaaaaaaaa-aaaaa/m%20edia/image34.png', skipping...
```

**Comment by jgm** [comment]
There's not much we can do about this.  The whole inline image won't fit, but line breaks in Markdown act like spaces.  We can't widen the cells because we try to respect column widths (this is significant with grid tables).

I recommend using `--reference-links` when you convert to md.  This should give you better results, because reference-link style images are shorter and more likely to fit in the table cells.

Another option would be to turn off grid tables, multiline tables, and simple tables; then you'll just get a pipe table with very long lines.  But this may not work well with the rest of your document.

**Comment by laperouse** [comment]
Thanks, --reference-links is a good idea. However, the docx to md generator produces this.

```
![]

  []: flowers-documentation-media/media/image201.png{width="2.0419520997375327in"
  height="2.3128226159230096in"}
```

the conversion from this md to docx fails because it says the file is not found. The size attributes it produced are misinterpreted. It looks like a space is missing between png and {.

**Comment by laperouse** [comment]
Another problem with --reference-links is that it does not detect correctly the scope of references, so it produces multiple times the same empty reference label for different images.
When i try to reparse this, it says there are duplicate references.
```
[pandoc warning] Duplicate link reference `[]' "source" (line 490, column 1)
```

for instance it produces this from a docx but cannot reparse it because of duplicate links:
```
![]

  []: aaaaaaa-aaaaaaaaaaaaaaaaaaa/media/image201.png {width="2.0419520997375327in"
  height="2.3128226159230096in"}
  
# titre1
![]

  []: aaaaaaa-aaaaaaaaaaaaaaaaaaa/media/image200.png {width="2.0419520997375327in"
  height="2.3128226159230096in"}
```

**Comment by jgm** [comment]
The bug with the missing space has been fixed
recently in the dev version.

**Comment by jgm** [comment]
I think this has been fixed, too.  Can you try with the
dev version?  If you don't want to compile from source,
you can get a binary from pandoc-nightlies
on GitHub.

+++ laperouse [May 17 17 02:28 ]:

**Comment by laperouse** [comment]
I confirm missing space is fixed with latest nightly build but not the issue with duplicate empty reference.

**Comment by jgm** [comment]
OK, I'm guessing you're using `--reference-location=section`?  Simple repro:

```
% pandoc --reference-links -t markdown --reference-location=section --atx-headers
# a
   
![](a)

# b

![](b)

^D
# a

![]

  []: a

# b

![]

  []: b
```

Without `--reference-location=section`, you don't get the duplicates.  So that's a bug that got introduced when we added that option.

**Comment by laperouse** [comment]
I used --reference-location=block

**Comment by laperouse** [comment]
About the missing space issue, there is still a problem with yesterdays build: depending on the length of the path, the attribute part may be sent to the next line. This is fine as long as the attribute starts on the same line as the path. But if the whole attributes are on next line, they are considered as text and written as text in the docx file.
with
```
pandoc.exe" -s -t markdown --reference-links --reference-location=block --extract-media=media -o source.md n.docx
```
this md can be produced by pandoc and is not valid:
```
![]

  []: media/92537e0a7e78e42a1b689a98a55fda95ec54194a.png 
  {width="2.6947364391951005in" height="2.6947364391951005in"}

```

also you can notice the image name is a hash which is strange because pandoc generate 2 images (for a single one in the document) one with the hash and one with a nice name but only the hash one is used.
````
pandoc: extracting media\92537e0a7e78e42a1b689a98a55fda95ec54194a.png
pandoc: extracting media\media\image1.png
````

**Comment by jgm** [comment]
Thanks for pointing these out -- I've now fixed both issues.
