### ISSUE TITLE
Cannot install with GHC 8.10

### ISSUE THREAD

**Issue by elliottslaughter** [jgm/pandoc#6455]
I'm hoping this is just a matter of bumping some dependency.

```
$ cabal install pandoc
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: pandoc-2.9.2.1 (user goal)
[__1] trying: zlib-0.6.2.1 (dependency of pandoc)
[__2] trying: base-4.14.0.0/installed-4.14.0.0 (dependency of zlib)
[__3] trying: time-1.9.3/installed-1.9.3 (dependency of pandoc)
[__4] next goal: haddock-library (dependency of pandoc)
[__4] rejecting: haddock-library-1.9.0 (conflict: pandoc =>
haddock-library>=1.8 && <1.9)
[__4] rejecting: haddock-library-1.8.0 (conflict:
base==4.14.0.0/installed-4.14.0.0, haddock-library => base>=4.7 && <4.14)
[__4] skipping: haddock-library-1.7.0, haddock-library-1.6.0,
haddock-library-1.5.0.1, haddock-library-1.4.5, haddock-library-1.4.4,
haddock-library-1.4.3, haddock-library-1.4.2, haddock-library-1.4.1,
haddock-library-1.2.1, haddock-library-1.2.0, haddock-library-1.1.1,
haddock-library-1.1.0, haddock-library-1.0.1, haddock-library-1.0.0,
haddock-library-1.6.1 (has the same characteristics that caused the previous
version to fail: excludes 'base' version 4.14.0.0)
[__4] fail (backjumping, conflict set: base, haddock-library, pandoc)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, pandoc, zlib,
pandoc:setup.Cabal, haddock-library, time, deepseq, array
Try running with --minimize-conflict-set to improve the error message.

$ cabal v1-install pandoc==2.9.2.1
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: pandoc-2.9.2.1 (user goal)
[__1] trying: zlib-0.6.2.1 (dependency of pandoc)
[__2] trying: base-4.14.0.0/installed-4.14.0.0 (dependency of zlib)
[__3] next goal: haddock-library (dependency of pandoc)
[__3] rejecting: haddock-library-1.9.0 (conflict: pandoc =>
haddock-library>=1.8 && <1.9)
[__3] rejecting: haddock-library-1.8.0 (conflict:
base==4.14.0.0/installed-4.14.0.0, haddock-library => base>=4.7 && <4.14)
[__3] skipping: haddock-library-1.7.0, haddock-library-1.6.0,
haddock-library-1.5.0.1, haddock-library-1.4.5, haddock-library-1.4.4,
haddock-library-1.4.3, haddock-library-1.4.2, haddock-library-1.4.1,
haddock-library-1.2.1, haddock-library-1.2.0, haddock-library-1.1.1,
haddock-library-1.1.0, haddock-library-1.0.1, haddock-library-1.0.0,
haddock-library-1.6.1 (has the same characteristics that caused the previous
version to fail: excludes 'base' version 4.14.0.0)
[__3] fail (backjumping, conflict set: base, haddock-library, pandoc)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: pandoc, base, haddock-library, zlib
Try running with --minimize-conflict-set to improve the error message.

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.1

$ cabal --version
cabal-install version 3.2.0.0
compiled using version 3.2.0.0 of the Cabal library 
```

This is on macOS 10.15 with GHC installed via Homebrew, in case that matters.

**Comment by mb21** [comment]
hm... not sure... but you've seen https://pandoc.org/installing.html? if you really need to build from source, try with stack?

**Comment by tarleb** [comment]
I think this is fixed with the version bump to haddock-library as done in 3f7f741297795ca343ed9fad3be0f3ca8fab4fd3. Not really a fan of hackage revisions, but doing this in a revision should fix the issue for 2.9.2.1 as well.

**Comment by elliottslaughter** [comment]
In my case I do need to build from source because I have to build filters against my installed version of Pandoc. I haven't tried stack yet, was hoping not to switch my workflow over (yet), but maybe I'll look into it at some point.

In the mean time, continuing on with my previous approach, this what I see when I try to build the latest master (de4fb05dc) from source:

```
$ cabal v1-install
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: pandoc-2.9.2.1 (user goal)
[__1] next goal: pandoc-types (dependency of pandoc)
[__1] rejecting: pandoc-types-1.20 (conflict: pandoc => pandoc-types>=1.21 &&
<1.22)
[__1] skipping: pandoc-types-1.17.6.1, pandoc-types-1.17.6,
pandoc-types-1.17.5.4, pandoc-types-1.17.5.3, pandoc-types-1.17.5.2,
pandoc-types-1.17.5.1, pandoc-types-1.17.5, pandoc-types-1.17.4.2,
pandoc-types-1.17.4.1, pandoc-types-1.17.4, pandoc-types-1.17.3.1,
pandoc-types-1.17.3, pandoc-types-1.17.2, pandoc-types-1.17.1,
pandoc-types-1.17.0.5, pandoc-types-1.17.0.4, pandoc-types-1.17.0.3,
pandoc-types-1.17.0.2, pandoc-types-1.17.0.1, pandoc-types-1.17,
pandoc-types-1.16.1.1, pandoc-types-1.16.1, pandoc-types-1.16.0.1,
pandoc-types-1.16, pandoc-types-1.12.4.7, pandoc-types-1.12.4.6,
pandoc-types-1.12.4.5, pandoc-types-1.12.4.4, pandoc-types-1.12.4.3,
pandoc-types-1.12.4.2, pandoc-types-1.12.4.1, pandoc-types-1.12.4,
pandoc-types-1.12.3.3, pandoc-types-1.12.3.2, pandoc-types-1.12.3.1,
pandoc-types-1.12.3, pandoc-types-1.12.2.3, pandoc-types-1.12.2.2,
pandoc-types-1.12.2.1, pandoc-types-1.12.2, pandoc-types-1.12.1.2,
pandoc-types-1.12.1.1, pandoc-types-1.12.1, pandoc-types-1.12,
pandoc-types-1.10, pandoc-types-1.9.1, pandoc-types-1.9.0.2,
pandoc-types-1.9.0.1, pandoc-types-1.9, pandoc-types-1.8.2,
pandoc-types-1.8.0.2, pandoc-types-1.8, pandoc-types-1.7, pandoc-types-1.19
(has the same characteristics that caused the previous version to fail:
excluded by constraint '>=1.21 && <1.22' from 'pandoc')
[__1] fail (backjumping, conflict set: pandoc, pandoc-types)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: pandoc, pandoc-types
```

Meanwhile, if I go directly to 3f7f741297795ca343ed9fad3be0f3ca8fab4fd3, I get:

```
$ cabal v1-install
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: pandoc-2.9.2.1 (user goal)
[__1] trying: zlib-0.6.2.1 (dependency of pandoc)
[__2] trying: base-4.14.0.0/installed-4.14.0.0 (dependency of zlib)
[__3] next goal: base-noprelude (dependency of pandoc)
[__3] rejecting: base-noprelude-4.13.0.0 (conflict:
base==4.14.0.0/installed-4.14.0.0, base-noprelude => base==4.13.0.0)
[__3] skipping: base-noprelude-4.12.0.0, base-noprelude-4.11.1.0,
base-noprelude-4.11.0.0, base-noprelude-4.10.1.0, base-noprelude-4.10.0.0,
base-noprelude-4.9.1.0, base-noprelude-4.9.0.0, base-noprelude-4.8.2.0,
base-noprelude-4.8.1.0, base-noprelude-4.8.0.0, base-noprelude-4.7.0.2,
base-noprelude-4.7.0.1, base-noprelude-4.7.0.0, base-noprelude-4.6.0.1,
base-noprelude-4.6.0.0, base-noprelude-4.5.1.0, base-noprelude-4.5.0.0,
base-noprelude-4.3.1.0, base-noprelude-4.3.0.0 (has the same characteristics
that caused the previous version to fail: excludes 'base' version 4.14.0.0)
[__3] fail (backjumping, conflict set: base, base-noprelude, pandoc)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: pandoc, base, base-noprelude, zlib
Try running with --minimize-conflict-set to improve the error message.
```

Any ideas?

**Comment by mb21** [comment]
> In my case I do need to build from source because I have to build filters against my installed version of Pandoc.

not sure I understand... the filters communicate with the pandoc binary over stdin/out... so no need to build from source? see https://pandoc.org/filters.html

**Comment by elliottslaughter** [comment]
The cache you're talking about is `~/.cabal`, right? I have tried removing that but still get the errors above.

I write filters in Haskell. See an example here: https://bitbucket.org/elliottslaughter/bookmd/src/master/etc/plugins/concat.hs

Currently my workflow is that I `cabal v1-install pandoc` and then `ghc --make` the filter. This is easier than setting up a whole build configuration for every filter I use; note that filters can be user-supplied in my system so there's not a bounded number of filters in general. (And I also don't want the filters to be built against a different Pandoc from what I have installed on the system.) In my experience this is the easiest way to do what I want, but perhaps there's something similar you can do with stack. But I know e.g. that `cabal v2-install` puts files in a strange place that then breaks the `ghc --make` command by default, and that's why I'm just cautious about running over to another solution right now. (But if there is a way to do this with stack I'm willing to hear it.)

**Comment by tarleb** [comment]
You may not need the full pandoc package. At least the `concat.hs` linked above would work with just `pandoc-types-1.20`.

**Comment by elliottslaughter** [comment]
Thanks, that seems to be a sufficient workaround for my use case.

I'll let you decide whether to keep this issue open or not.

**Comment by mb21** [comment]
btw. seems our CI is running cabal successfully? https://github.com/jgm/pandoc/runs/754729153

    cabal v2-build --dependencies-only --enable-tests --disable-optimization

**Comment by jgm** [comment]
You need to use cabal v2, since the current master HEAD depends on an unreleased version of pandoc-types.

**Comment by jgm** [comment]
Might be worth doing a hackage revision with
```
aeson >= 0.7 && < 1.6,
base64-bytestring >= 0.1 && < 1.2,
haddock-library >= 1.8 && < 1.10,
```
but I don't know if that would solve all the ghc 8.10 issues.

Probably better just to do a new release.

I'd been planning to wait til we had more of the table stuff implemented, in case we need further changes to pandoc-types, but maybe it's okay.

**Comment by GeorgeCo** [comment]
I use cabal v1-install due to issues with ghc-pkg. With ghc 8.10.1 it fails to install with 

 cabal v1-install pandoc
Resolving dependencies...
Starting     pandoc-1.9.4.3
Failed to install pandoc-1.9.4.3
Build log ( /Users/gcolpitts/.cabal/logs/ghc-8.10.1/pandoc-1.9.4.3-GKcE6LvbU1k55vThF6GVPD.log ):
cabal: Entering directory '/var/folders/df/5d_dsdrx1dn4j30ktsgn8blh0000gp/T/cabal-tmp-13205/pandoc-1.9.4.3'
cabal: Leaving directory '/var/folders/df/5d_dsdrx1dn4j30ktsgn8blh0000gp/T/cabal-tmp-13205/pandoc-1.9.4.3'
cabal: Error: some packages failed to install:
pandoc-1.9.4.3-GKcE6LvbU1k55vThF6GVPD failed during the configure step. The
exception was:
dieVerbatim: user error (cabal: '/usr/local/bin/ghc' exited with an error:

/var/folders/df/5d_dsdrx1dn4j30ktsgn8blh0000gp/T/cabal-tmp-13205/pandoc-1.9.4.3/dist/setup/setup.hs:10:33:
error:
Module
‘Distribution.Simple.GHC’
does not export
‘ghcPackageDbOptions’
|
10 | import Distribution.Simple.GHC (ghcPackageDbOptions)
| ^^^^^^^^^^^^^^^^^^^

/var/folders/df/5d_dsdrx1dn4j30ktsgn8blh0000gp/T/cabal-tmp-13205/pandoc-1.9.4.3/dist/setup/setup.hs:19:1:
error:
Could not find module ‘System.Time’
Perhaps you meant
System.CPUTime (from base-4.14.0.0)
System.Cmd (from process-1.6.8.2)
System.Mem (from base-4.14.0.0)
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
19 | import System.Time
| ^^^^^^^^^^^^^^^^^^
)

**Comment by tarleb** [comment]
@GeorgeCo Looks like you are trying to compile pandoc version 1.9.4.3. That version is almost 8 years old and shouldn't be expected to work. The issue at hand is about compiling the latest pandoc release.

**Comment by GeorgeCo** [comment]
@tarleb, thanks for the quick reply! I should have noted that my command to compile the latest version of pandoc didn't do that but instead tried to compile a really old version. I don't understand why it did that. Any suggestions as to how I can  fix that? My guess is that I should delete some directories in ~/.cabal but I'm not sure which directories are safe to delete.

When I do  cabal v1-install pandoc==2.9.2.1 ' I run into the same issue as the OP

**Comment by mb21** [comment]
> When I do cabal v1-install pandoc==2.9.2.1 . I run into the same issue as the OP

yes, you need cabal v2

but also for you: are you sure you need to compile from source? see https://pandoc.org/installing.html

**Comment by nshepperd** [comment]
Github HEAD seems to build on 8.10.1. What *doesn't* is the latest release on hackage (2.9.2.1), which also prevents from building things depending on pandoc, such as hakyll. Any chance of a minor release to hackage to make 8.10 work?

**Comment by jgm** [comment]
Yes, I'm hoping to do that soon.

**Comment by tonyday567** [comment]
I couldn't find a pandoc release that builds with the latest stackage nightlies, which are ghc-8.10.  Note that pandoc itself has been excluded from the nightlies for the last week or so due to a dependency on base-noprelude.

I could build pandoc from HEAD with a few extra-deps in stack.yaml:

```
resolver: nightly-2020-06-27

extra-deps:
  - git: https://github.com/jgm/pandoc
    commit: cd3941d34e578f2ebd4dd11484fc26c7afae8a6a
  - hslua-1.1.2
  - jira-wiki-markup-1.3.2
```

**Comment by jgm** [comment]
I'm still hoping to make a new release soon -- just waiting on a couple things.

**Comment by jgm** [comment]
Fixed with 2.10

**Comment by GeorgeCo** [comment]
2.10 compiles on ghc 8.10. It may be worth noting that memory use goes to 4.5 GB while compiling pandoc itself at the end.

**Comment by jgm** [comment]
@GeorgeCo are you reporting that it takes significantly more memory to compile pandoc 2.10 using ghc 8.10 than with ghc 8.8?  Or that it takes more memory to compile 2.10 than 2.9.x?

If the former, I'm sure ghc devs would be interested in hearing about it.

**Comment by ickc** [comment]
I think since pandoc ~2.8 the memory use to compile pandoc already surpassed 4GiB. I didn’t compare across GHC versions though. I *guess* the increase in memory use is mainly from pandoc, not GHC.

**Comment by GeorgeCo** [comment]
@jgm Sorry I don't know how much memory it took on previous versions. 4.5 GB seems to indicate a problem to me; I'm not sure when it started. I  agree it is probably a ghc issue not a pandoc one. There is already a ghc bug about how much memory vector takes. There was some improvement in that case post ghc 8.10.1. I just wanted to let people know in case somebody was interested in investigating and constructing a smaller case for ghc.

**Comment by jgm** [comment]
@GeorgeCo what OS are you using?

**Comment by GeorgeCo** [comment]
@jgm macos 10.15.5
