### ISSUE TITLE
Missing mime type for .fgb FlatGeobuf

### ISSUE THREAD

**Issue by rressler** [jgm/pandoc#7202]
request .fgb be added to pandoc mime types
.fgb is not in the table of mime types  for pandoc 2.13
.fgb is produced by the Rmapview package 2.9
Example: put the following in a text file

---
title: "mapview test"
output: html_document
---
```{r}
library(mapview)
mapviewOptions(fgb=TRUE)
mapview(franconia)
```
Then knit to HTML with the rmarkdown package

**Comment by jgm** [comment]
So, what is the MIME type that goes with fgb extension? And where is this documented?
fgb isn't in the giant table of mime types in my `/etc/mime.types`.

**Comment by rressler** [comment]
John, I checked with the developers of the .fgb output files and it turns out they have not obtained an official mime type yet. Sounds like someone can close out my request as it cannot be met until the .fgb actually has a IME type.
Thanks,
Richard

From: John MacFarlane ***@***.***>
Reply-To: jgm/pandoc ***@***.***>
Date: Sunday, April 4, 2021 at 12:25 AM
To: jgm/pandoc ***@***.***>
Cc: Richard Ressler ***@***.***>, Author ***@***.***>
Subject: Re: [jgm/pandoc] Missing mime type for .fgb FlatGeobuf (#7202)


External Email: Use caution with links and attachments.

So, what is the MIME type that goes with fgb extension? And where is this documented?
fgb isn't in the giant table of mime types in my /etc/mime.types.

**Comment by jgm** [comment]
Actually, looking at the code,
``` hs
      mime <- case (mimetype, respMime) of
                ("",Nothing) -> throwError $ PandocSomeError
                  $ "Could not determine mime type for `" <> src <> "'"
                (x, Nothing) -> return x
                (_, Just x ) -> return x
      result <- if "text/css" `T.isPrefixOf` mime
                then do
                  oldInputs <- getInputFiles
                  setInputFiles [T.unpack src]
                  res <- cssURLs (takeDirectory $ T.unpack src) raw'
                  setInputFiles oldInputs
                  return res
               else return raw'
```
it's not completely clear to me why we couldn't just `return raw'` for cases where we can't determine the mime type, instead of halting with an error.  The only reason we're getting the mime type is to see if it's CSS.

**Comment by jgm** [comment]
I pushed a fix that may or may not work for your case; you can test with a nightly after tonight.

**Comment by rressler** [comment]
John,
Thanks!
Richard
From: John MacFarlane ***@***.***>
Reply-To: jgm/pandoc ***@***.***>
Date: Monday, April 5, 2021 at 11:50 AM
To: jgm/pandoc ***@***.***>
Cc: Richard Ressler ***@***.***>, Author ***@***.***>
Subject: Re: [jgm/pandoc] Missing mime type for .fgb FlatGeobuf (#7202)


External Email: Use caution with links and attachments.

I pushed a fix that may or may not work for your case; you can test with a nightly after tonight.

**Comment by rressler** [comment]
John,
I have to figure out how to install the nightly over top of my current pandoc. I followed here<https://github.com/jgm/pandoc/blob/master/INSTALL.md> using stack and adding the ~/.local/bin to my path but I think I might have to uninstall pandoc and start over to get a clean setup.
Thanks,
Richard


From: John MacFarlane ***@***.***>
Reply-To: jgm/pandoc ***@***.***>
Date: Monday, April 5, 2021 at 11:50 AM
To: jgm/pandoc ***@***.***>
Cc: Richard Ressler ***@***.***>, Author ***@***.***>
Subject: Re: [jgm/pandoc] Missing mime type for .fgb FlatGeobuf (#7202)


External Email: Use caution with links and attachments.

I pushed a fix that may or may not work for your case; you can test with a nightly after tonight.

**Comment by donojazz** [comment]
I updated my pandoc yesterday, used mapview 2.9 in R and still crashed. My solution was to go back to mapview 2.7.8.  Worked fine.
