### ISSUE TITLE
Citeproc gets confused by percent signs in fields

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#7678]
BibTeX seems to allow escaped percent signs in most fields (most notably, abstracts) and unescaped percent signs in URLs. In both cases, these cause parse errors in citeproc.

Input:

``` bibtex
@misc{doe,
  author = "Jane Doe",
  title = "Work",
  year = "2021",
  url = {https://example.com/%a8},
  abstract = {Improvements of 5{\%}.}
}
```

Result:

```
$ pandoc percent.bib -t json
Error at "percent.bib" (line 9, column 1):
unexpected end of input
```

I confirmed that the input works fine with bibtex.

**Comment by frederik** [comment]
Dear John and Albert, I am unsure whether this is the same issue but

```
@misc{doe,
  author = "Jane Doe",
  title = "Work",
  year = "2021",
  url = "%20and%20"
}
```

does not work (while url = {%20and%20} does)

The same .bib file is accepted in biblatex (file was exported from the app Paperpile). Happy to open a new issue if you think this should be fixed inside of pandoc.

**Comment by jgm** [comment]
I don't think biblatex accepts this. Anyway, biber throws a warning and ignores the whole citation
```
WARN - BibTeX subsystem: /tmp/biber_tmp_zdL2/2eb9d1a305a2386b1298af4ff7c24292_68470.utf8, line 26, warning: 559 characters of junk seen at toplevel
ERROR - BibTeX subsystem: /tmp/biber_tmp_zdL2/2eb9d1a305a2386b1298af4ff7c24292_68470.utf8, line 26, syntax error: found "}", expected ","
INFO - WARNINGS: 1
```

**Comment by frederik** [comment]
Interesting. It did render in Overleaf.

```
\documentclass{article}
\usepackage[
backend=biber,
style=alphabetic,
]{biblatex}
\title{A bibLaTeX example}
\addbibresource{7678.bib}

\begin{document}

Testing \cite{doe} 

\printbibliography

\end{document}
```

[exp.pdf](https://github.com/jgm/pandoc/files/9556783/exp.pdf)

What would be your recommendation? Raise an issue in Paperpile to escape the URLs?

**Comment by jgm** [comment]
OK, trying your example, it works for me too.  I must have made a mistake before.

**Comment by jdutant** [comment]
This issue still affects the doi field (tested with Pandoc 3.0.1). Input:

``` bibtex
@misc{doe,
  author = "Jane Doe",
  title = "Work AGAIN",
  year = "2021",
  doi = {10.1007%2FBF00126690},
  abstract = {Improvements of 5{\%}.}
}
```

Result:

```
$ pandoc -t json percent.bib 
Error at "percent.bib" (line 9, column 1):
unexpected end of input
```

The `.bib` file works with biber and if we add hyperref the link resolves correctly:

```
\documentclass{article}
\usepackage{hyperref}
\usepackage[
backend=biber,
style=alphabetic,
]{biblatex}
\title{A bibLaTeX example}
\addbibresource{percent.bib}

\begin{document}

Testing \cite{doe} 

\printbibliography

\end{document}
```

[test.pdf](https://github.com/jgm/pandoc/files/10561243/test.pdf)
